Algoritmo "Exercicio_5"

Var
   num, pula:inteiro


Inicio
   escreval ("Digite o número para ser imprimido de 0 até N:")
   leia (num)
   limpatela

   escreval ("Digite de quanto em quanto vai pular, ex: 2:")
   leia (pula)
   limpatela

   escreval ("O número",num,", pulando de",pula," em",pula," será imprimido:")
   para num de 0 ate num passo pula faca
      escreva (num)
   fimpara


Fimalgoritmo